[theme]
primaryColor="#F97316"
backgroundColor="#F9FAFB"
secondaryBackgroundColor="#FFFFFF"
textColor="#0F172A"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
